services:

  # <========================================================Partie base de données========================================================>
  sqldatabase:
    image: mariadb:11
    restart: always
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--connect" ]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/identifiant-sql-secrets
    volumes:
      - sqldb-data:/var/lib/mysql
      - ./initialisation_db:/docker-entrypoint-initdb.d:ro
    networks:
      - db-net
    secrets:
      - identifiant-sql-secrets

  nosqldatabase:
    image: mongo:6.0
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/identifiant-nosql-secrets
    volumes:
      - nosqldb-data:/data/db
    networks:
      - db-net
    secrets:
      - identifiant-nosql-secrets

  # <========================================================Partie Soutien au dev et à l'admin========================================================>
  phpmyadmin:
    image: phpmyadmin:latest
    profiles: [ "dev-tool" ]
    ports:
      - "127.0.0.1:8081:80"
    environment:
      - PMA_HOST=sqldatabase
    networks:
      - db-net
    depends_on:
      - sqldatabase

  mongo-express:
    image: mongo-express:latest
    profiles: [ "dev-tool" ]
    ports:
      - "127.0.0.1:8082:8081"
    networks:
      - db-net
    depends_on:
      nosqldatabase:
        condition: service_healthy
    secrets:
      - source: mongo_express_config
        target: /app/config.js

  # <========================================================Partie Application et API========================================================>
  broker:
    image: rabbitmq:3.12-management-alpine
    container_name: logistico-broker
    networks:
      - broker-net
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: always
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_stomp tcp_listeners [6163]"
    volumes:
      - broker-data:/var/lib/rabbitmq
    secrets:
      - rabbit_user
      - rabbit_password

  restapi:
    build: ./RESTApi
    container_name: logistico-restapi
    restart: always
    depends_on:
      sqldatabase:
        condition: service_healthy
      nosqldatabase:
        condition: service_healthy
    networks:
      - db-net
      - frontend-net
    secrets:
      - db_prod_creds
      - db_history_creds

volumes:
  sqldb-data:
  nosqldb-data:
  broker-data:


networks:
  db-net:
  broker-net:
  frontend-net:


secrets:
  identifiant-sql-secrets:
    file: ./secrets/identifiant-sql-secrets.txt
  identifiant-nosql-secrets:
    file: ./secrets/identifiant-nosql-secrets.txt
  mongo_express_config:
    file: ./secrets/mongo-express-config.js
  rabbit_user:
    file: ./secrets/rabbit_user.txt
  rabbit_password:
    file: ./secrets/rabbit_password.txt
  db_prod_creds:
    file: ./secrets/db_prod_creds_secrets.txt
  db_history_creds:
    file: ./secrets/db_history_creds_secrets.txt
