spring.application.name=RealtimeApi
server.port=8080
spring.profiles.active=development

server.servlet.session.cookie.name=logisticoRTAPi
server.servlet.session.cookie.max-age=7200
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict

spring.datasource.username=root
spring.datasource.password=df85_Klo92_admin_sql
spring.datasource.url=jdbc:mariadb://sqldatabase:3306/logistico_train
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.data.mongodb.database=history-db
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.host=nosqldatabase
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=root
spring.data.mongodb.password=admin123

spring.rabbitmq.host=broker
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbituser2403
spring.rabbitmq.password=rabbitpassword0579

app.broker.host=broker
app.broker.port=61613
app.broker.login=rabbituser2403
app.broker.password=rabbitpassword0579